[tool.poetry]
name = "header-adder"
version = "0.1.0"
description = ""
authors = ["IJN Akashi AR <gcciscool@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
