#+OPTIONS: toc:nil num:nil
#+REVERSE_DATETREE_DATE_FORMAT: %Y-%m-%d %A
#+REVERSE_DATETREE_WEEK_FORMAT: %Y W%W
#+REVERSE_DATETREE_YEAR_FORMAT: %Y
#+REVERSE_DATETREE_USE_WEEK_TREE: t
#+TITLE: daily
# To add an entry use org-reverse-datetree-go-to-date-in-file

I write about what's happening in my life.

* 2024

** 2024 W09

*** 2024-03-02 Saturday
Working on a networking assignment.

Feeling stressed out due to some issues at home. It's hard to focus when things seem overwhelming.

Fleshed out the "about me" page. It feels nice to write.  

*** 2024-03-01 Friday
Woke up in a bad mood today. Read a bit of pbrt. I need to get started on a networking assignment.

I am a noob when it comes to CS/math and I would like to learn more about it. Occasionally I get motivated to start learning about a topic but I find it hard to keep the motivation after a while. It is a bit difficult for me to keep track of progress and perhaps I have too little attention span to persist through the duller chapters of some of the textbooks. Having this daily writing thing might help me be more mindful of my learning goals, even if no one reads it.

Had a long day today, but it was interesting.

*** 2024-02-29 Thursday
Have a headache today. Finished an assignment.

Had an idea about writing a literate programming tangler that takes markdown files and generates full programs from source code blocks, similar to how Org mode does it. But I would just be making something similar to what OM already has, and I probably wouldn't even use it. That made me wonder if the reason why a lot of my personal projects end up unfinished is because I won't really use them in the first place. So I tried thinking about writing something that could really improve my life, but I couldn't really think of anything.

Wrote some more code for my MC sampler thing. I want it to be able to compute the integral for an arbitrary function so I wrote a mini-language description for a simple RPN calculator. Still need to write the parser and interpreter.

*** 2024-02-28 Wednesday
Working on some assignments. 

*** 2024-02-27 Tuesday
Just finished setting up the blog. I wonder if I'm restricting myself too much by using pure org mode tools. Now to study for a midterm tomorrow...

I didn't think too hard about what I want to gain from creating this website. Just a place to dump some thoughts and to get some introspection I guess. I don't know.
